// console.log("this is js console")
// const heading=document.getElementById("head-1")
// const heading2=document.getElementsByClassName("head-2")
// const tagElements=document.getElementsByTagName("h3")
// console.log(heading)
// console.log(heading2[0])
// console.log(tagElements[0])
// const heading=document.querySelectorAll("p.para")
// const heading=document.getElementById("head").innerText
// console.log(heading)
// const heading=document.createElement("h1")
// heading.innerText="Satish"
// const me=heading.classList
// me.add("color")
// me.add("bg")
// me.remove("color")
// // heading.setAttribute("class","color")
// const htmlbody=document.getElementById('body')
// console.log(htmlbody)
// htmlbody.appendChild(heading)
const HtmlBody=document.getElementById("body")
const parent1=document.createElement("div")
parent1.setAttribute("class","parent-1")
const parent2=document.createElement("div")
parent2.setAttribute("class","parent-2")
const parent3=document.createElement("div")
parent3.setAttribute("class","parent-3")
const childDiv1=document.createElement("div")
childDiv1.setAttribute("class","childDiv-1")
const childDiv2=document.createElement("div")
childDiv2.setAttribute("class","childDiv-2")
const childDiv3=document.createElement("div")
childDiv3.setAttribute("class","childDiv-3")
const childheading1=document.createElement("h1")
const childheading2=document.createElement("h3")
childheading1.innerText="this is heading one"
childheading2.innerText="this is heading three"
HtmlBody.appendChild(parent1)
parent1.appendChild(parent2)
parent2.appendChild(parent3)
parent3.appendChild(childDiv1)
childDiv1.appendChild(childDiv2)
childDiv2.appendChild(childheading1)
childDiv2.appendChild(childheading2)
childDiv1.appendChild(childDiv3)


